-- Supabase 대시보드 > SQL Editor 에서 이 스크립트를 실행하세요.

-- 1) 신청 내역 테이블
create table if not exists public.applications (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  name        text not null,
  email       text not null,
  phone       text,
  department  text,
  program     text not null,          -- 입문반 / 실전반 / 심화반 (실제 배포된 테이블 컬럼명)
  message     text
);

-- 최신순 조회 성능을 위한 인덱스
create index if not exists applications_created_at_idx
  on public.applications (created_at desc);

-- 2) Row Level Security 활성화
alter table public.applications enable row level security;

-- 3) 정책
--    anon 키로 신청(INSERT)과 조회(SELECT)를 허용합니다.
--    (실서비스에서는 관리자 조회를 별도 인증으로 보호하는 것을 권장합니다.)
create policy "Allow anonymous insert"
  on public.applications
  for insert
  to anon
  with check (true);

create policy "Allow anonymous select"
  on public.applications
  for select
  to anon
  using (true);
